#!/usr/bin/env node

require('./helpers/polyfill');

const cli = require('@vbarbarosh/node-helpers/src/cli');
const ffprobe = require('@vbarbarosh/ffmpeg-helpers/src/ffprobe');
const shell_ffmpeg_progress = require('@vbarbarosh/ffmpeg-helpers/src/shell_ffmpeg_progress');
const shell_json = require('@vbarbarosh/node-helpers/src/shell_json');
const user_friendly_status = require('./helpers/user_friendly_status');

cli(main);

async function main()
{
    const fm = process.argv[2];
    const args = process.argv.slice(3);
    const input = args[args.indexOf('-i') + 1];
    await shell_ffmpeg_progress(args, {
        probe: await shell_json(ffprobe({input})),
        user_friendly_status: s => user_friendly_status(fm.replaceAll('{}', s)),
    });
}
