#!/usr/bin/env node

require('./helpers/polyfill');

const cli = require('@vbarbarosh/node-helpers/src/cli');
const shell_curl_progress = require('@vbarbarosh/node-helpers/src/shell_curl_progress');
const user_friendly_status = require('./helpers/user_friendly_status');

cli(main);

async function main()
{
    const fm = process.argv[2];
    await shell_curl_progress(process.argv.slice(3), {
        user_friendly_status: s => user_friendly_status(fm.replaceAll('{}', s)),
    });
}
