#!/usr/bin/env node

require('./helpers/polyfill');

const cli = require('@vbarbarosh/node-helpers/src/cli');
const format_seconds = require('@vbarbarosh/node-helpers/src/format_seconds');
const shell_thru = require('@vbarbarosh/node-helpers/src/shell_thru');
const user_friendly_status = require('./helpers/user_friendly_status');

cli(main);

async function main()
{
    const time0 = Date.now();
    const fm = process.argv[2];
    const timer = setInterval(tick, 1000);
    try {
        tick();
        await shell_thru(process.argv.slice(3)).promise();
        tick();
    }
    finally {
        clearInterval(timer);
    }
    function tick() {
        const seconds = (Date.now() - time0)/1000;
        user_friendly_status(fm.replaceAll('{}', format_seconds(seconds)));
    }
}
