#!/usr/bin/env node

require('./polyfill');

const cli = require('@vbarbarosh/node-helpers/src/cli');
const ffprobe = require('@vbarbarosh/ffmpeg-helpers/src/ffprobe');
const fs = require('fs');
const shell_ffmpeg_progress = require('@vbarbarosh/ffmpeg-helpers/src/shell_ffmpeg_progress');
const shell_json = require('@vbarbarosh/node-helpers/src/shell_json');

cli(main);

async function main()
{
    const fm = process.argv[2];
    const args = process.argv.slice(3);
    const input = args[args.indexOf('-i') + 1];
    await shell_ffmpeg_progress(args, {
        probe: await shell_json(ffprobe({input})),
        user_friendly_status: s => user_friendly_status(fm.replaceAll('{}', s)),
    });
}

// Treat /dev/fd/3 as a special file for user-friendly messages.
// But, if no such file was open, print use-friendly messages to the stderr.
function user_friendly_status(s)
{
    const tmp = s + '\n';
    fs.write(3, tmp, function (error) {
        if (error) {
            process.stderr.write(tmp);
        }
    });
}
