#!/usr/bin/env node

require('./polyfill');

const cli = require('@vbarbarosh/node-helpers/src/cli');
const fs = require('fs');
const shell_curl_progress = require('@vbarbarosh/node-helpers/src/shell_curl_progress');

cli(main);

async function main()
{
    const fm = process.argv[2];
    await shell_curl_progress(args.slice(3), {
        user_friendly_status: s => user_friendly_status(fm.replaceAll('{}', s)),
    });
}

// Treat /dev/fd/3 as a special file for user-friendly messages.
// But, if no such file was open, print use-friendly messages to the stderr.
function user_friendly_status(s)
{
    const tmp = s + '\n';
    fs.write(3, tmp, function (error) {
        if (error) {
            process.stderr.write(tmp);
        }
    });
}
